### ISSUE TITLE
suggestion: adding social contact details logo/gif rather than visible link 

### ISSUE THREAD

**Issue by NirmalSilwal** [abhishekrawat22/abhishekrawat22#1]
Hi @abhishekrawat22 , I think adding hyperlink of contact logo would be much better for Linkedln, twitter, instagram and medium profiles in readme.

What do you think?

reference:  you can check [my profile reamde](https://github.com/NirmalSilwal/NirmalSilwal) for reference of contact logo.

Thanks

**Comment by abhishekrawat22** [comment]
Yeah, thanks for the suggestion. Will look into it.
